### ISSUE TITLE
ep_author_follow Settings not honoured

### ISSUE THREAD

**Issue by grawert** [ether/ep_author_follow#7]
I am installing the plugin via admin interface and adding the following to settings.json and reload. But in settings panel  both Follow Author(s) and  Follow All Authors are enabled by default.

settings.json:
```json
{
  /*
   * Plugin: Author Follow
   */
  "ep_author_follow": {
    "followAll" : false,
    "enableFollow" : false
  }
}
```

**Comment by JohnMcLear** [comment]
What did you expect the behavior to be here btw?  I find those settings weird, it's always disabled by default 📦

**Comment by grawert** [comment]
Seems I've been a bit hasty. I build the docker image from the current master of https://github.com/ether/etherpad-lite.
When installing ep_author_follow from /admin interface and load a pad I see CLIENT_VARS.data and it the following is set:

```json
"ep_author_follow":{"followAll":false,"enableFollow":true}
```

I tried to overwrite without luck. No matter what I set on the Settings page in the admin/settings interface. Do you have any hints what I am doing wrong here?

**Comment by JohnMcLear** [comment]
I think the biggest question is.  How do you expect these settings to behave?  What behaviour do you experience you want to change??

**Comment by grawert** [comment]
The Pad Settings show:

Enable Following: enabled
Follow All Changes: enabled

I would like them to be disabled by default.

**Comment by JohnMcLear** [comment]
What difference does that make to behaviour?

**Comment by grawert** [comment]
If I disable both options my pad does not follow the changes made by someone else. If enabled the pad follows the lines of someone else changing it.

**Comment by JohnMcLear** [comment]
oh, I didn't realize it was so enthusiastic by default 🍡 Yea, I will fix this ASAP! 😄

**Comment by grawert** [comment]
Cool! Many thanks!

**Comment by JohnMcLear** [comment]
I pushed a new version, should be fixed :)

**Comment by grawert** [comment]
I have configured in settings.json:
"ep_author_follow":{"followAll":false,"enableFollow":false}

That is also working. By default the follow function is disabled. But in the pad settings panel both "Follow Author(s)" and "Follow All Authors" are shown as enabled. And if I switch them off, the follow function is turned on. So these are in reverse!?

**Comment by JohnMcLear** [comment]
should be fixed :)

**Comment by grawert** [comment]
Yes. Many thanks John!
